---
title: "The Code"
editor: 
  markdown: 
    wrap: 72
---

library(ggplot2) library(plotly)

data \<- read.csv('leclerc.csv') data2 \<- read.csv('sainz.csv')

ggplot(data, aes(x = Year, y = Points)) + geom_bar(stat = "identity",
fill = "red", width = 0.6) + geom_text(aes(label = Points), vjust =
-0.5, color = "black", size = 5, fontface = 'bold') + labs(x = "Year", y
= "Points", title = "Leclerc Points after first 3 Races") + theme_bw() +
theme(plot.title = element_text(hjust = 0.5, face = 'bold')) +
scale_y_continuous(breaks = seq(0, 100, by = 5)) + theme(plot.title =
element_text(hjust = 0.5, face = "bold"), axis.text.x =
element_text(color = "#6a0dad", size = 12, angle = 45, hjust = 1), \#
X-axis text color and angle axis.text.y = element_text(color =
"#6a0dad", size = 12), \# Y-axis text color axis.title =
element_text(color = "#6a0dad", size = 14), \# Axis title color and size
panel.background = element_rect(fill = "#f5f0f5")) \# Background color

ggplot(data, aes(x = Year)) + geom_line(aes(y = Points, color =
"Line")) + \# Line plot geom_bar(aes(y = Points, fill = "Bar"), stat =
"identity", width = 0.5, color = "red") + \# Bar plot
scale_fill_manual(values = "red") + \# Bar color
scale_color_manual(values = "#6a0dad") + \# Line color geom_text(aes(y =
Points, label = Points), vjust = -0.5, size = 4, fontface = "bold",
color = "black") + \# Add counts on top of the bars with bold font and
increased size labs(x = "Year", y = "Points", title = "Leclerc Points
after first 3 Races") + theme_minimal() + theme(plot.title =
element_text(hjust = 0.5, face = "bold"), axis.text.x =
element_text(size = 12, angle = 45, hjust = 1), \# X-axis text size and
angle axis.text.y = element_text(size = 12), \# Y-axis text size
axis.title = element_text(size = 14), \# Axis title size
panel.background = element_rect(fill = "#f5f0f5")) \# Background color

ggplot(data2, aes(x = Year, y = Points)) + geom_bar(stat = "identity",
fill = "red", width = 0.6) + geom_text(aes(label = Points), vjust =
-0.5, color = "black", size = 5, fontface = 'bold') + labs(x = "Year", y
= "Points", title = "Sainz Points after first 3 Races") + theme_bw() +
theme(plot.title = element_text(hjust = 0.5, face = 'bold')) +
scale_y_continuous(breaks = seq(0, 100, by = 5)) + theme(plot.title =
element_text(hjust = 0.5, face = "bold"), axis.text.x =
element_text(color = "#6a0dad", size = 12, angle = 45, hjust = 1), \#
X-axis text color and angle axis.text.y = element_text(color =
"#6a0dad", size = 12), \# Y-axis text color axis.title =
element_text(color = "#6a0dad", size = 14), \# Axis title color and size
panel.background = element_rect(fill = "#f5f0f5")) \# Background color

ggplot(data3, aes(x = Year)) + geom_line(aes(y = Points, color =
"Line")) + \# Line plot geom_bar(aes(y = Points, fill = "Bar"), stat =
"identity", width = 0.5, color = "red") + \# Bar plot
scale_fill_manual(values = "red") + \# Bar color
scale_color_manual(values = "#6a0dad") + \# Line color geom_text(aes(y =
Points, label = Points), vjust = -0.5, size = 4, fontface = "bold",
color = "black") + \# Add counts on top of the bars with bold font and
increased size labs(x = "Year", y = "Points", title = "Sainz Points
after first 3 Races") + theme_minimal() + theme(plot.title =
element_text(hjust = 0.5, face = "bold"), axis.text.x =
element_text(size = 12, angle = 45, hjust = 1), \# X-axis text size and
angle axis.text.y = element_text(size = 12), \# Y-axis text size
axis.title = element_text(size = 14), \# Axis title size
panel.background = element_rect(fill = "#f5f0f5")) \# Background color
